### ISSUE TITLE
Auto-detect EmptinessManipulator

### ISSUE THREAD

**Issue by J-Richter** [Sedeniono/tiny-optional#3]
Suppose I have a custom class 'PayloadType' with a custom manipulator 'EmptinessManipulator'.
Is there a way to teach tiny-optional to automatically use EmptinessManipulator when tiny::optional<PayloadType> is used? 
So I dont want to specify the additional template argument EmptinessManipulator.

I can imagine providing a template specialization somewhere might do the trick. But I found nothing mentioned in the docs and I dont want to rely on implementation details.

**Comment by Sedeniono** [comment]
That is something that also I thought would be very nice to have. But so far I have simply not implemented it yet. The only way one can currently use some custom logic is via `tiny::optional_inplace` and specifying an `EmptinessManipulator` as the second template argument. 

I will have a closer look how difficult it would be to implement some customization point for `tiny::optional` itself. The major concern with stuff like this is usually to get the "lookup" right (so that one does not rely on e.g. the order of header includes).

**Comment by J-Richter** [comment]
I could imagine from the user's point of view that one has to specialize lazy::EmptinessManipulator, similar to std::less or std::hash. lazy::optional<> would then use this specialization if available. This could also cover the case for double, bool, etc., right? The default-template would then simply fall-back to use the variant with indicator variable.

**Comment by Sedeniono** [comment]
@J-Richter Sorry that it took me so long, but other things kept me busy. I just pushed a [new release](https://github.com/Sedeniono/tiny-optional/releases/tag/v1.1.0), see [tag v1.1.0](https://github.com/Sedeniono/tiny-optional/releases/tag/v1.1.0). The new version introduces `tiny::optional_flag_manipulator` which can be specialized to teach `tiny::optional` (and `tiny::optional_aip`) about a custom payload type. If the specialization exists, then `sizeof(tiny::optional<PayloadType>) == sizeof(PayloadType)`. See the updated [readme](https://github.com/Sedeniono/tiny-optional#teaching-tinyoptional-about-custom-types-tinyoptional_flag_manipulator) for more information.

Originally, I wanted to not use the specialization approach but rather one based on ADL (argument dependent lookup). Basically, the user would provide some overload `CustomFlagManipulator GetTinyOptionalInplaceFlagManipulator(PayloadType)`. The library would have never called the function, but used it to link the `PayloadType` to the `CustomFlagManipulator` at compile time. The advantage would have been that it did not require an additional `#include` on the user's side. It actually worked fine, but MSVC, clang and gcc all complained in all sorts of ways about declared functions without definitions or unused functions. Forcing users to deal with them seemed not very reasonable. So instead I switched to the specialization approach similar to  [`std::hash`](https://en.cppreference.com/w/cpp/utility/hash) or [`fmt::formatter`](https://fmt.dev/latest/api.html#formatting-user-defined-types), as you also suggested. The downside is that the original template `tiny::optional_flag_manipulator` needs to be known before the user can specialize it, meaning that the user needs to include either `tiny/optional.h` or the new header `tiny/optional_flag_manipulator_fwd.h`.

**Comment by J-Richter** [comment]
@Sedeniono I think the interface is much better now. Thanks for the implementation! I already integrated the new version in our code base. Works without problems.
