### ISSUE TITLE
Support building without the platform specific optimizations?

### ISSUE THREAD

**Issue by mjoras** [Sedeniono/tiny-optional#7]
Right now inclusion of the header completely fails when not on an x86 based platform. However the majority of the facilities actually work great on ARM, as can be seen by just `#if 0` out those pieces.

Would it be reasonable, instead of using #error, instead making it so compilation of those specific constructs fails if on an unsupported platform?

**Comment by mjoras** [comment]
> What is your use case? Do you want the "custom sentinel" functionality available on ARM? And/or do you have a code base that is compiled for both x86 and ARM, and you don't care that e.g. tiny::optional<double> would have a different size on these platforms?

This is essentially the use case. We have a codebase that builds on both x86 and ARM. We care about memory usage on both, and don't particularly care about the size of tiny::optional<double>. The majority of our use case is of types like e.g. tiny::optional_aip<uint64_t>. There's a couple cases where we could use the custom member sentinel, but it's still nice to have ARM support for the other things without that. Right now I have the things under the X86 guards ifdef'd out and things work fine on ARM.

**Comment by Sedeniono** [comment]
@mjoras I just published [version 1.3.0](https://github.com/Sedeniono/tiny-optional/releases/tag/v1.3.0). You can disable the undefined behavior tricks (unused bit patterns; storing the empty state in a member variable) by defining `TINY_OPTIONAL_USE_SEPARATE_BOOL_INSTEAD_OF_UB_TRICKS`. This allows compilation and usage of the sentinel/`tiny::optional_flag_manipulator` features on non-x86/x64 platforms.
Hope this helps!
